@baseUrl=https://ez-json-demo.herokuapp.com/api
# Categories

# @name getAllCategories
GET {{baseUrl}}/categories

###

# @name addNewCategory
POST {{baseUrl}}/categories
Content-Type: application/json

{
    "name": "Laptop2"
}

###

# @name updateCategory
PATCH  {{baseUrl}}/categories/2
Content-Type: application/json

{
    "name": "New Laptop"
}

###

# @name removeCategory
DELETE  {{baseUrl}}/categories/2
Content-Type: application/json




